# Generated by Django 5.2.6 on 2025-09-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
    ]
